package org.mini2Dx.injection;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a class as a prototype bean. All prototype beans are backed by a pool
 * of prepared instances that are removed from the pool when the bean is requested. Removed
 * instances are then replaced with new instances generated by another thread.
 * 
 * @see <a href="http://en.wikipedia.org/wiki/Prototype_pattern">Prototype
 *      Pattern</a>
 * 
 * @author Thomas Cashman
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Prototype {
	/**
	 * Returns the size of the prototype instance pool
	 * 
	 * @return 2 by default
	 */
	int poolSize() default 2;
}
